// Generated by dts-bundle v0.7.3

declare module 'betting' {
    import { IBettingConfig } from "betting/api/IBettingConfig";
    import { IBettingModule } from "betting/api/IBettingModule";
    export class BettingModule implements IBettingModule {
        initialize(container: HTMLElement, config: IBettingConfig): void;
        show(): Promise<void>;
    }
}

declare module 'betting/api/IBettingConfig' {
    import { IAnalytics } from "betting/api/IAnalytics";
    export interface IBettingConfig {
        debug: boolean;
        maxWidth: number;
        locale: string;
        teams: ITeam[];
        analytics: IAnalytics;
        preferredBookmakers: IBookmaker[];
    }
    export interface ITeam {
        id: string;
        colors: string[];
    }
    export interface IBookmaker {
        id: string;
        referId: string;
    }
}

declare module 'betting/api/IBettingModule' {
    import { IBettingConfig } from "betting/api/IBettingConfig";
    export interface IBettingModule {
        initialize(container: HTMLElement, config: IBettingConfig): void;
        show(): Promise<void>;
    }
}

declare module 'betting/api/IAnalytics' {
    export interface IAnalytics {
        track(eventName: string, params: any): void;
    }
}

